 #include    "..\TKS_GLOBE_VARIES.H"
 #include    "..\MAIN_PROGRAM_V103\MAIN_PROGRAM_V103.H" 
 //#include    "..\BS82C16A_LIBV413\BS82C16A_LIBV413.CEX" 
 
 
#define u8 unsigned char 
#define u16 unsigned short
#define BIT(x) ((u8)(1<<x))
#define true 1
#define false 0
 
 

#include    "AppMain.H" 
#include    "led.H" 
#include    "key.H" 
#include    "timer.H" 
#include    "peripheral.H" 
#include    "selftest.H" 
#include    "uart.H" 